### ISSUE TITLE
Differential equations of PSDM

### ISSUE THREAD

**Issue by YunhaoYuan** [USEPA/Water_Treatment_Models#7]
Dear authors, 

I am really interested in the PSDM model that you have implemented in this project. Would you please share some reference materials for the PSDM, especially the partial differential equations and the boundary conditions on the axial and radial directions?  I wish I can have a better understanding of your codes by cross-referencing the theories and your great implementation.

Thanks a lot in advance.

**Comment by ucchejbb** [comment]
@YunhaoYuan Thank you for your interest in the PSDM code. The original implementation was developed at Michigan Technological University. Drs. David Hand and John Crittenden along with many others helped to develop that original code base. You can find more information with the User Manual for ETDOT (https://github.com/USEPA/Environmental-Technologies-Design-Option-Tool) specifically AdDesignS.

A few other (definitely not exhaustive) citations to look at are:
https://www.sciencedirect.com/science/article/abs/pii/S0043135405001776
https://www.sciencedirect.com/science/article/abs/pii/S0273122397001364

As I recall, the Jarvie et al., 2005 paper had a lot of good citations from their previous work (link above) and would likely be a good place to look for more information after the User Manual for AdDesignS.

**Comment by YunhaoYuan** [comment]
> @YunhaoYuan Thank you for your interest in the PSDM code. The original implementation was developed at Michigan Technological University. Drs. David Hand and John Crittenden along with many others helped to develop that original code base. You can find more information with the User Manual for ETDOT (https://github.com/USEPA/Environmental-Technologies-Design-Option-Tool) specifically AdDesignS.
> 
> A few other (definitely not exhaustive) citations to look at are: https://www.sciencedirect.com/science/article/abs/pii/S0043135405001776 https://www.sciencedirect.com/science/article/abs/pii/S0273122397001364
> 
> As I recall, the Jarvie et al., 2005 paper had a lot of good citations from their previous work (link above) and would likely be a good place to look for more information after the User Manual for AdDesignS.

Thank you for the reference materials! Have a great day!
